# Generated by Django 2.2 on 2020-06-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200609_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comlete',
            new_name='comlpete',
        ),
    ]
