# Generated by Django 2.2 on 2020-06-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200610_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comlpete',
            new_name='complete',
        ),
    ]
